import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#374a4d",
        "surface-container": "#eceeec",
        "on-surface-variant": "#434843",
        "primary-container": "#1b3022",
        "secondary-fixed-dim": "#d9c2b2",
        surface: "#f8faf8",
        "on-error-container": "#93000a",
        secondary: "#6c5b4e",
        "on-primary-container": "#819986",
        "on-error": "#ffffff",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#f6decd",
        outline: "#737973",
        "on-tertiary-container": "#829699",
        "inverse-surface": "#2e3130",
        "tertiary-fixed": "#d2e6ea",
        "surface-container-high": "#e6e9e7",
        "on-background": "#191c1b",
        "tertiary-container": "#1c2e31",
        "on-primary-fixed": "#0b2013",
        "surface-container-lowest": "#ffffff",
        background: "#f8faf8",
        "tertiary-fixed-dim": "#b6cacd",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#364c3c",
        primary: "#061b0e",
        "surface-container-low": "#f2f4f2",
        "on-surface": "#191c1b",
        "on-secondary-container": "#726153",
        "outline-variant": "#c3c8c1",
        "surface-container-highest": "#e1e3e1",
        "surface-variant": "#e1e3e1",
        tertiary: "#06191c",
        "surface-bright": "#f8faf8",
        "primary-fixed-dim": "#b4cdb8",
        "primary-fixed": "#d0e9d4",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#eff1ef",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#534437",
        "on-secondary": "#ffffff",
        "on-tertiary-fixed": "#0b1e21",
        "inverse-primary": "#b4cdb8",
        "on-secondary-fixed": "#25190f",
        "surface-dim": "#d8dad9",
        "surface-tint": "#4d6453",
        "secondary-container": "#f6decd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        sm: "12px",
        xs: "4px",
        gutter: "24px",
        base: "8px",
        xl: "80px",
        "margin-mobile": "20px",
        lg: "48px",
        "container-max": "1280px",
        md: "24px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "body-lg": ["var(--font-hanken)", "sans-serif"],
        "body-md": ["var(--font-hanken)", "sans-serif"],
        "label-md": ["var(--font-hanken)", "sans-serif"],
        "label-sm": ["var(--font-hanken)", "sans-serif"],
        "headline-md": ["var(--font-garamond)", "serif"],
        "headline-sm": ["var(--font-garamond)", "serif"],
        "display-lg": ["var(--font-garamond)", "serif"],
        "display-lg-mobile": ["var(--font-garamond)", "serif"],
        serif: ["var(--font-garamond)", "serif"],
        sans: ["var(--font-hanken)", "sans-serif"],
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": [
          "14px",
          { lineHeight: "20px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "label-sm": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "500" },
        ],
        "headline-md": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-sm": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": [
          "48px",
          { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "500" },
        ],
        "display-lg-mobile": [
          "36px",
          { lineHeight: "42px", letterSpacing: "-0.01em", fontWeight: "500" },
        ],
      },
    },
  },
  plugins: [],
};

export default config;
